### PR TITLE
Fix empty form action urls

### PR DESCRIPTION
**Pull request by geoffbeier**
This PR does 4 things:

1. Make sure the variables passed to the `url` parameter of the `form` component are initialized.
2. Consistently names those variables `action_url` to make them easier to spot if this crops up again.
3. Adds django-fastdev as a dev dependency. (It uses the git master branch for now, as the ignore feature needed to make it compatible with the use of slippers in django-allauth-ui is only in master, not in a release.)
4. Adds `django_fastdev` to `THIRD_PARTY_APPS` in `tests/settings.py` along with `BASE_DIR` and `FASTDEV_IGNORED_TEMPLATES` settings that make fastdev work here.

It addresses issue #96.

### CODE REVIEW

**Comment by geoffbeier** [comment]
This should fix #94, which is really the same issue.

**Comment by danihodovic** [comment]
I will have a look at this in the coming week or two. I left the urls empty because that's what allauth does. The change looks OK from afar, I'll take a closer look later.

Is it possible to enable django-fastdev only in development and not force the package on users that install allauth-ui?

**Comment by geoffbeier** [comment]
> Is it possible to enable django-fastdev only in development and not force the package on users that install allauth-ui?

Yes. I believe by including it in the section `tool.poetry.group.dev.dependencies` with pytest, we have done exactly that.

**Comment by danihodovic** [comment]
Is this failure related to your change?

https://github.com/danihodovic/django-allauth-ui/actions/runs/9927816285/job/27479602943?pr=97#step:10:25

**Comment by geoffbeier** [comment]
> Is this failure related to your change?
> 
> https://github.com/danihodovic/django-allauth-ui/actions/runs/9927816285/job/27479602943?pr=97#step:10:25

No. When I run the following:

```sh
# check out clean copy of master branch
git clone git@github.com:danihodovic/django-allauth-ui.git
cd django-allauth-ui
poetry install
poetry shell
python ./manage.py validate_templates
```

I see the same TemplateSyntaxErrors:

```
/Users/geoff/Library/Caches/pypoetry/virtualenvs/django-allauth-ui-7KxvM1DS-py3.12/lib/python3.12/site-packages/allauth/account/app_settings.py:53: UserWarning: settings.ACCOUNT_LOGIN_ATTEMPTS_LIMIT/TIMEOUT is deprecated, use: settings.ACCOUNT_RATE_LIMITS['login_failed']
  warnings.warn(
System check identified some issues:

WARNINGS:
?: (slippers.E001) Slippers was unable to find a components.yaml file.
	HINT: Make sure it's in a root template directory.
/Users/geoff/bug_reproductions/ci_dj_allauth_ui/django-allauth-ui/allauth_ui/templates/socialaccount/connections.html: TemplateSyntaxError Invalid block tag on line 20: 'var', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
/Users/geoff/Library/Caches/pypoetry/virtualenvs/django-allauth-ui-7KxvM1DS-py3.12/lib/python3.12/site-packages/allauth/templates/usersessions/usersession_list.html: TemplateSyntaxError 'humanize' is not a registered tag library. Must be one of:
account
admin_list
admin_modify
admin_urls
allauth
allauth_ui
cache
debugger_tags
django_browser_reload
highlighting
i18n
indent_text
l10n
log
rosetta
slippers
socialaccount
static
syntax_color
tz
widget_tweaks
widont
CommandError: 2 errors found

```

I don't mind looking into those... want me to roll a fix for them into this PR or do you want a separate PR since it's an unrelated issue?

**Comment by danihodovic** [comment]
Nah, let's do a separate PR

**Comment by danihodovic** [comment]
I've deployed it to https://django-allauth-ui.hodovi.ch/. Can you have a quick glance to help me confirm that it works?

**Comment by geoffbeier** [comment]
- [X] Signup has the right action
- [X] Emails has the right action

- Connected Social Accounts gives a server error 500, so I couldn't see 

- [X] Change Password has the right action action
- [X] Password reset has has the right action
- [X] Set Password has the right action
- [X] Reauthenticate has the right action
- [X] Logout has the right action

- Email verification sent has no form
- Password reset done has no form
- Password reset from key done has no form
- Account inactive has no form
- Social account metadata says I need to login

That all looks correct to me.

**Comment by danihodovic** [comment]
Thanks Geoff. It's been released as 1.1.7 https://pypi.org/project/django-allauth-ui/1.1.7/

**Comment by geoffbeier** [comment]
Thank you very much for making time to work through this with me.

**Comment by danihodovic** [comment]
It's easy when the patch is well prepared. Geoff the gentleman

**Pull request merged**
